import { useEffect, useMemo, useState } from 'react';
import { CalendarClock, Check, Eye, ImagePlus, Megaphone, Pencil, Plus, RefreshCw, Save, Timer, Trash2, X } from 'lucide-react';
import { deleteCampaign, loadAdminCampaigns, saveCampaign, uploadCampaignImage, type CampaignInput, type PlatformCampaign } from '../lib/campaigns';
import './AdminCampaignManager.css';

const empty:CampaignInput={kind:'announcement',placement:'top_bar',title:'',subtitle:'',imageUrl:'',linkUrl:'/buscar',linkLabel:'Saiba mais',theme:'indigo',priority:0,isActive:false,isDismissible:true,startsAt:null,endsAt:null};
const localValue=(value:string|null)=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
const isoValue=(value:string)=>value?new Date(value).toISOString():null;
const dateFmt=new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'});
function statusOf(item:PlatformCampaign){const now=Date.now();if(!item.isActive)return{label:'Inativo',className:'is-off'};if(item.startsAt&&new Date(item.startsAt).getTime()>now)return{label:'Agendado',className:'is-scheduled'};if(item.endsAt&&new Date(item.endsAt).getTime()<=now)return{label:'Encerrado',className:'is-ended'};return{label:'No ar',className:'is-live'};}

export function AdminCampaignManager({query='',onError}:{query?:string;onError:(message:string)=>void}){
  const[items,setItems]=useState<PlatformCampaign[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[editor,setEditor]=useState<CampaignInput|null>(null),[uploading,setUploading]=useState(false);
  const refresh=async()=>{setLoading(true);try{setItems(await loadAdminCampaigns())}catch(error:unknown){onError((error as {message?:string})?.message||'Falha ao carregar campanhas.')}finally{setLoading(false)}};
  useEffect(()=>{let active=true;loadAdminCampaigns().then(rows=>{if(active)setItems(rows)}).catch((error:unknown)=>{if(active)onError((error as {message?:string})?.message||'Falha ao carregar campanhas.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[onError]);
  const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase('pt-BR');return q?items.filter(item=>`${item.title} ${item.subtitle||''} ${item.kind}`.toLocaleLowerCase('pt-BR').includes(q)):items},[items,query]);
  const edit=(item:PlatformCampaign)=>setEditor({...item});
  const persist=async()=>{if(!editor)return;if(editor.title.trim().length<3){onError('Informe um título com pelo menos 3 caracteres.');return;}setBusy(true);const result=await saveCampaign(editor);setBusy(false);if(result.error){onError(result.error);return;}setEditor(null);await refresh()};
  const remove=async(item:PlatformCampaign)=>{if(!window.confirm(`Excluir permanentemente “${item.title}”?`))return;setBusy(true);const result=await deleteCampaign(item.id);setBusy(false);if(result.error){onError(result.error);return;}await refresh()};
  const toggle=async(item:PlatformCampaign)=>{setBusy(true);const result=await saveCampaign({...item,isActive:!item.isActive});setBusy(false);if(result.error){onError(result.error);return;}await refresh()};
  const upload=async(file?:File)=>{if(!file||!editor)return;setUploading(true);const result=await uploadCampaignImage(file);setUploading(false);if(result.error){onError(result.error);return;}setEditor(current=>current?{...current,imageUrl:result.url}:current)};

  return <div className="acm-page">
    <section className="acm-summary"><div><Megaphone/><span><strong>{items.length}</strong><small>campanhas</small></span></div><div><Eye/><span><strong>{items.filter(i=>statusOf(i).className==='is-live').length}</strong><small>no ar agora</small></span></div><div><CalendarClock/><span><strong>{items.filter(i=>statusOf(i).className==='is-scheduled').length}</strong><small>agendadas</small></span></div><button onClick={()=>setEditor({...empty})}><Plus/>Nova campanha</button></section>
    <section className="acm-toolbar"><div><small>PUBLICIDADE E AVISOS</small><h2>Banners da plataforma</h2><p>Defina o período e a prioridade. A campanha de maior prioridade aparece primeiro.</p></div><button onClick={()=>void refresh()} disabled={loading}><RefreshCw className={loading?'spin':''}/>Atualizar</button></section>
    {loading?<div className="acm-empty"><RefreshCw className="spin"/><strong>Carregando campanhas…</strong></div>:filtered.length?<div className="acm-grid">{filtered.map(item=>{const status=statusOf(item);return <article key={item.id} className="acm-card">
      <div className={`acm-preview theme-${item.theme}`}>{item.imageUrl?<img src={item.imageUrl} alt=""/>:<><Megaphone/><span><strong>{item.title}</strong><small>{item.subtitle||'Sem texto complementar'}</small></span></>}</div>
      <div className="acm-card__body"><header><span className={`acm-status ${status.className}`}><i/>{status.label}</span><small>{item.kind==='advertisement'?'Propaganda':'Aviso'}</small></header><h3>{item.title}</h3><p>{item.subtitle||'Sem descrição complementar.'}</p><dl><div><dt><Timer/>Início</dt><dd>{item.startsAt?dateFmt.format(new Date(item.startsAt)):'Imediato'}</dd></div><div><dt><Timer/>Fim</dt><dd>{item.endsAt?dateFmt.format(new Date(item.endsAt)):'Sem prazo'}</dd></div><div><dt>Prioridade</dt><dd>{item.priority}</dd></div></dl></div>
      <footer><button onClick={()=>void toggle(item)} disabled={busy}>{item.isActive?<X/>:<Check/>}{item.isActive?'Desativar':'Ativar'}</button><button onClick={()=>edit(item)}><Pencil/>Editar</button><button className="danger" onClick={()=>void remove(item)} disabled={busy}><Trash2/>Excluir</button></footer>
    </article>})}</div>:<div className="acm-empty"><Megaphone/><strong>Nenhuma campanha encontrada</strong><p>Crie o primeiro banner ou ajuste sua busca.</p><button onClick={()=>setEditor({...empty})}><Plus/>Criar campanha</button></div>}

    {editor&&<div className="acm-modal" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setEditor(null)}}><form className="acm-editor" role="dialog" aria-modal="true" aria-labelledby="acm-editor-title" onSubmit={event=>{event.preventDefault();void persist()}}><header><div><small>GESTOR DE CAMPANHAS</small><h2 id="acm-editor-title">{editor.id?'Editar banner':'Nova campanha'}</h2></div><button type="button" onClick={()=>setEditor(null)} aria-label="Fechar"><X/></button></header><div className="acm-form">
      <label>Tipo<select value={editor.kind} onChange={e=>setEditor({...editor,kind:e.target.value as CampaignInput['kind']})}><option value="announcement">Aviso institucional</option><option value="advertisement">Propaganda</option></select></label><label>Tema<select value={editor.theme} onChange={e=>setEditor({...editor,theme:e.target.value as CampaignInput['theme']})}><option value="indigo">Azul institucional</option><option value="emerald">Verde</option><option value="amber">Âmbar</option><option value="slate">Grafite</option></select></label>
      <label className="wide">Título<input required minLength={3} maxLength={120} value={editor.title} onChange={e=>setEditor({...editor,title:e.target.value})} placeholder="Ex.: Festival do Açaí em Feijó"/></label><label className="wide">Texto complementar<input maxLength={180} value={editor.subtitle||''} onChange={e=>setEditor({...editor,subtitle:e.target.value})} placeholder="Uma frase curta e objetiva"/></label>
      <div className="wide acm-field"><span>Imagem do banner</span><div className="acm-upload"><input aria-label="URL da imagem do banner" value={editor.imageUrl||''} onChange={e=>setEditor({...editor,imageUrl:e.target.value})} placeholder="URL da imagem ou envie um arquivo"/><label className="acm-upload__button"><ImagePlus/>{uploading?'Enviando…':'Enviar imagem'}<input aria-label="Enviar arquivo de imagem" type="file" accept="image/png,image/jpeg,image/webp,image/avif" disabled={uploading} onChange={e=>void upload(e.target.files?.[0])}/></label></div><small>PNG, JPG, WebP ou AVIF, até 8 MB. Recomendado: 1024 × 62 px.</small></div>
      <label>Destino<input required value={editor.linkUrl} onChange={e=>setEditor({...editor,linkUrl:e.target.value})} placeholder="/buscar ou https://…"/></label><label>Texto do botão<input maxLength={40} value={editor.linkLabel} onChange={e=>setEditor({...editor,linkLabel:e.target.value})}/></label>
      <label>Início<input type="datetime-local" value={localValue(editor.startsAt)} onChange={e=>setEditor({...editor,startsAt:isoValue(e.target.value)})}/></label><label>Encerramento<input type="datetime-local" value={localValue(editor.endsAt)} onChange={e=>setEditor({...editor,endsAt:isoValue(e.target.value)})}/></label><label>Prioridade<input type="number" min="0" max="999" value={editor.priority} onChange={e=>setEditor({...editor,priority:Number(e.target.value)||0})}/></label>
      <div className="acm-switches"><label><input aria-label="Campanha ativa" type="checkbox" checked={editor.isActive} onChange={e=>setEditor({...editor,isActive:e.target.checked})}/><span><strong>Campanha ativa</strong><small>Será exibida dentro do período configurado.</small></span></label><label><input aria-label="Permitir fechar banner" type="checkbox" checked={editor.isDismissible} onChange={e=>setEditor({...editor,isDismissible:e.target.checked})}/><span><strong>Permitir fechar</strong><small>Fecha nas abas abertas e reaparece ao atualizar a página.</small></span></label></div>
    </div><footer><button type="button" onClick={()=>setEditor(null)}>Cancelar</button><button className="primary" type="submit" disabled={busy||uploading}>{busy?<RefreshCw className="spin"/>:<Save/>}{editor.id?'Salvar alterações':'Criar campanha'}</button></footer></form></div>}
  </div>;
}
