import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { useGSAP, gsap, ScrollTrigger } from "../lib/lightMotion";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { Bot, Building2, CheckCircle2, LoaderCircle, Minus, PackagePlus, PiggyBank, Plus, Save, Search, Send, ShoppingBasket, Sparkles, Store, Trash2, WalletCards, X } from "lucide-react";
import { fetchCatalog } from "../data/remoteCatalog";
import type { Product, ProductOffer } from "../data/catalog";
import { loadSessionProfile, supabase, type SessionProfile } from "../lib/roles";
import { AppDock, PublicFooter, PublicHeader } from "./ReferenceExperience";
import "./SmartBasketPage.css";

gsap.registerPlugin(ScrollTrigger);

const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
type Essential={key:string;label:string;keywords:string[];priority:number;quantity:(people:number)=>number};
type DesiredRow={label:string;product:Product;quantity:number;priority:number};
type PlannedItem={product:Product;quantity:number;offer:ProductOffer;subtotal:number;essential:string};
type Plan={strategy:"multi_store"|"single_store";total:number;items:PlannedItem[];stores:string[];missing:string[];savings:number;label:string;storeName?:string};
const ESSENTIALS:Essential[]=[
{key:"arroz",label:"Arroz",keywords:["arroz"],priority:1,quantity:p=>Math.max(1,Math.ceil(p/3))},{key:"feijao",label:"Feijão",keywords:["feijao"],priority:2,quantity:p=>Math.max(1,Math.ceil(p/2))},{key:"oleo",label:"Óleo",keywords:["oleo de soja","oleo"],priority:3,quantity:p=>Math.max(1,Math.ceil(p/2))},{key:"macarrao",label:"Macarrão",keywords:["macarrao"],priority:4,quantity:p=>Math.max(1,Math.ceil(p*1.5))},{key:"leite",label:"Leite",keywords:["leite integral","leite"],priority:5,quantity:p=>Math.max(1,p*2)},{key:"acucar",label:"Açúcar",keywords:["acucar"],priority:6,quantity:p=>Math.max(1,Math.ceil(p/2))},{key:"cafe",label:"Café",keywords:["cafe"],priority:7,quantity:p=>Math.max(1,Math.ceil(p/2))},{key:"farinha",label:"Farinha",keywords:["farinha de trigo","farinha"],priority:8,quantity:()=>1},{key:"sal",label:"Sal",keywords:["sal refinado","sal"],priority:9,quantity:()=>1},{key:"proteina",label:"Proteína",keywords:["frango","carne bovina","carne"],priority:10,quantity:p=>Math.max(1,Math.ceil(p/2))},{key:"ovos",label:"Ovos",keywords:["ovos","ovo"],priority:11,quantity:p=>Math.max(1,Math.ceil(p/3))},{key:"detergente",label:"Detergente",keywords:["detergente"],priority:12,quantity:p=>Math.max(1,Math.ceil(p/2))},{key:"sabao",label:"Sabão",keywords:["sabao em po","sabao"],priority:13,quantity:()=>1},{key:"papel",label:"Papel higiênico",keywords:["papel higienico"],priority:14,quantity:()=>1}];
function candidateFor(products:Product[],essential:Essential){return products.filter(product=>{const text=normalize(`${product.name} ${product.category} ${product.brand}`);return essential.keywords.some(k=>text.includes(normalize(k)))&&product.minPrice>0;}).sort((a,b)=>a.minPrice-b.minPrice||a.name.localeCompare(b.name,"pt-BR"))[0]||null;}
function cheapestOffer(product:Product):ProductOffer|null{return product.offers?.filter(o=>o.value>0).sort((a,b)=>a.value-b.value)[0]||(product.minPrice>0?{establishmentId:product.establishmentId,establishmentSlug:product.establishmentSlug,establishment:product.establishment,neighborhood:product.neighborhood,storeColor:product.storeColor,value:product.minPrice,capturedAt:product.capturedAt}:null);}
function suggestedRows(products:Product[],people:number):DesiredRow[]{return ESSENTIALS.map(e=>{const product=candidateFor(products,e);return product?{label:e.label,product,quantity:e.quantity(people),priority:e.priority}:null;}).filter(Boolean) as DesiredRow[];}
function buildMulti(rows:DesiredRow[],budget:number):Plan{const items:PlannedItem[]=[];const missing:string[]=[];let total=0;for(const row of rows){const offer=cheapestOffer(row.product);if(!offer){missing.push(row.label);continue;}let added=0;for(let i=0;i<row.quantity;i++){if(total+offer.value>budget)break;total+=offer.value;added++;}if(added)items.push({product:row.product,quantity:added,offer,subtotal:offer.value*added,essential:row.label});else missing.push(row.label);}return{strategy:"multi_store",total,items,stores:[...new Set(items.map(i=>i.offer.establishment))],missing,savings:0,label:"Menor preço em várias lojas"};}
function buildSingle(rows:DesiredRow[],budget:number):Plan{const stores=new Set<string>();rows.forEach(r=>r.product.offers?.forEach(o=>stores.add(o.establishment)));let best:Plan|null=null;let bestScore=-1;for(const storeName of stores){const items:PlannedItem[]=[];const missing:string[]=[];let total=0;let score=0;for(const row of rows){const offer=row.product.offers?.find(o=>o.establishment===storeName);if(!offer){missing.push(row.label);continue;}let added=0;for(let i=0;i<row.quantity;i++){if(total+offer.value>budget)break;total+=offer.value;added++;}if(added){items.push({product:row.product,quantity:added,offer,subtotal:offer.value*added,essential:row.label});score+=(110-row.priority)*1000+added;}else missing.push(row.label);}if(!best||score>bestScore||(score===bestScore&&total<best.total)){bestScore=score;best={strategy:"single_store",total,items,stores:items.length?[storeName]:[],missing,savings:0,label:"Melhor cesta em uma loja",storeName};}}return best||{strategy:"single_store",total:0,items:[],stores:[],missing:rows.map(r=>r.label),savings:0,label:"Melhor cesta em uma loja"};}
function readStoredPrefill(){try{const raw=sessionStorage.getItem("precocerto:smart-basket-prefill");return raw?JSON.parse(raw) as {budget?:number;people?:number}:{};}catch{return{};}}
export function SmartBasketPage(){
const pageRef=useRef<HTMLDivElement>(null);
const navigate=useNavigate();const[searchParams]=useSearchParams();const stored=useMemo(readStoredPrefill,[]);const initialBudget=Math.max(50,Number(searchParams.get("budget")||stored.budget||350));const initialPeople=Math.min(8,Math.max(1,Number(searchParams.get("people")||stored.people||2)));
const[profile,setProfile]=useState<SessionProfile|null>(null),[authLoading,setAuthLoading]=useState(true),[products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true);const[budget,setBudget]=useState(initialBudget),[income,setIncome]=useState<number|"">(""),[people,setPeople]=useState(initialPeople),[selected,setSelected]=useState<"multi_store"|"single_store">("multi_store"),[saving,setSaving]=useState(false),[message,setMessage]=useState("");const[selectionMode,setSelectionMode]=useState<"smart"|"custom">("smart"),[query,setQuery]=useState(""),[custom,setCustom]=useState<Record<string,number>>({});
const[assistantOpen,setAssistantOpen]=useState(false),[assistantInput,setAssistantInput]=useState(""),[assistantLog,setAssistantLog]=useState<AssistantTurn[]>([{from:"assistant",text:"Olá! Posso sugerir itens, buscar um produto ou ajustar seu orçamento. O que você precisa?"}]);
const assistantLogRef=useRef<HTMLDivElement>(null);
useEffect(()=>{assistantLogRef.current?.scrollTo({top:assistantLogRef.current.scrollHeight});},[assistantLog,assistantOpen]);
useEffect(()=>{loadSessionProfile().then(p=>{setProfile(p);setAuthLoading(false);if(!p)navigate(`/login?redirect=${encodeURIComponent(`/cesta-inteligente?budget=${budget}&people=${people}`)}`,{replace:true});});},[navigate,budget,people]);
useEffect(()=>{fetchCatalog().then(c=>setProducts(c.products)).finally(()=>setLoading(false));},[]);useEffect(()=>{sessionStorage.setItem("precocerto:smart-basket-prefill",JSON.stringify({budget,people}));},[budget,people]);
const suggestedBudget=useMemo(()=>income?Math.max(50,Math.round(Number(income)*.25)):null,[income]);
const customRows=useMemo(()=>Object.entries(custom).map(([id,quantity],index)=>{const product=products.find(p=>String(p.id)===id);return product?{label:product.name,product,quantity,priority:index+1}:null;}).filter(Boolean) as DesiredRow[],[custom,products]);const rows=useMemo(()=>selectionMode==="custom"?customRows:suggestedRows(products,people),[selectionMode,customRows,products,people]);
const searchResults=useMemo(()=>{const q=normalize(query);if(q.length<2)return[];return products.filter(p=>p.minPrice>0&&normalize(`${p.name} ${p.brand} ${p.category}`).includes(q)&&!custom[p.id]).sort((a,b)=>a.minPrice-b.minPrice).slice(0,8);},[query,products,custom]);
const multi=useMemo(()=>buildMulti(rows,Math.max(0,budget)),[rows,budget]),single=useMemo(()=>buildSingle(rows,Math.max(0,budget)),[rows,budget]);const baseline=Math.max(multi.total,single.total);multi.savings=Math.max(0,baseline-multi.total);single.savings=Math.max(0,baseline-single.total);const active=selected==="multi_store"?multi:single;
function addProduct(product:Product){setSelectionMode("custom");setCustom(current=>({...current,[product.id]:current[product.id]||1}));setQuery("");}
function askAssistant(raw:string){const text=raw.trim();if(!text)return;const reply=assistantReply(text,{products,budget,people,active,multi,single,setBudget,setSelectionMode,setSelected,addProduct});setAssistantLog(current=>[...current,{from:"user",text},{from:"assistant",text:reply}]);setAssistantInput("");}
function submitAssistant(event:FormEvent){event.preventDefault();askAssistant(assistantInput);}function changeQty(id:string,delta:number){setCustom(current=>{const next=Math.max(0,(current[id]||1)+delta);const copy={...current};if(!next)delete copy[id];else copy[id]=next;return copy;});}
const ASSISTANT_CHIPS=["Sugerir itens essenciais","Qual o jeito mais econômico?","O que ainda falta na cesta?","Buscar arroz"];
type AssistantTurn={from:"user"|"assistant";text:string};
function assistantReply(input:string,ctx:{products:Product[];budget:number;people:number;active:Plan;multi:Plan;single:Plan;setBudget:(v:number)=>void;setSelectionMode:(v:"smart"|"custom")=>void;setSelected:(v:"multi_store"|"single_store")=>void;addProduct:(p:Product)=>void}):string{
const text=normalize(input);
if(!text)return"Pode perguntar sobre um produto, um valor em reais, ou pedir a opção mais econômica.";
const asksMissing=/falta|faltando|pendente/.test(text);
if(asksMissing){const balance=Math.max(0,ctx.budget-ctx.active.total);if(!ctx.active.missing.length)return`Sua cesta atual atende todos os itens sugeridos, com ${brl.format(balance)} de saldo no orçamento.`;return`Ainda ${ctx.active.missing.length===1?"falta":"faltam"} ${ctx.active.missing.length} ${ctx.active.missing.length===1?"item":"itens"} (${ctx.active.missing.slice(0,4).join(", ")}). Saldo disponível: ${brl.format(balance)}.`;}
const asksEssentials=/essencia|sugest[aã]o|sugerir|monte|montar/.test(text);
if(asksEssentials){ctx.setSelectionMode("smart");return"Troquei para a sugestão inteligente com os itens essenciais para o número de pessoas informado. Ajuste o orçamento acima se quiser recalcular.";}
const asksCheap=/econom|barato|mais barato|menor pre[cç]o/.test(text);
if(asksCheap){ctx.setSelected("multi_store");return`A opção de maior economia soma ${brl.format(ctx.multi.total)} em ${ctx.multi.stores.length} ${ctx.multi.stores.length===1?"loja":"lojas"}.`;}
const asksSingle=/uma loja|mesma loja|pratic|um só lugar|um so lugar/.test(text);
if(asksSingle){ctx.setSelected("single_store");return ctx.single.storeName?`A melhor combinação em uma loja só é em ${ctx.single.storeName}, somando ${brl.format(ctx.single.total)}.`:"Ainda não encontrei uma loja que cubra bem sua lista sozinha — tente aumentar o orçamento.";}
const budgetMatch=text.match(/(\d{2,6})/);
if(budgetMatch&&/reais|orcamento|gastar|r\$/.test(text)){const value=Math.max(10,Number(budgetMatch[1]));ctx.setBudget(value);return`Orçamento ajustado para ${brl.format(value)}.`;}
const essential=ESSENTIALS.find(e=>e.keywords.some(k=>text.includes(normalize(k))));
if(essential){const product=candidateFor(ctx.products,essential);if(product){ctx.addProduct(product);return`Adicionei ${product.name} (a partir de ${brl.format(product.minPrice)}) à sua cesta.`;}return`Não encontrei ${essential.label.toLocaleLowerCase("pt-BR")} com preço cadastrado no catálogo agora.`;}
const found=ctx.products.filter(p=>p.minPrice>0&&normalize(`${p.name} ${p.brand} ${p.category}`).includes(text)).sort((a,b)=>a.minPrice-b.minPrice)[0];
if(found){ctx.addProduct(found);return`Adicionei ${found.name} (a partir de ${brl.format(found.minPrice)}) à sua cesta.`;}
if(budgetMatch){const value=Math.max(10,Number(budgetMatch[1]));ctx.setBudget(value);return`Orçamento ajustado para ${brl.format(value)}.`;}
return"Não encontrei esse produto no catálogo. Tente outro nome, ou peça 'itens essenciais', 'mais economia' ou 'uma loja só'.";
}
// Entrada suave da hero, dos controles de orçamento e do seletor de
// estratégia ao montar a página. Respeita prefers-reduced-motion e usa só
// transform/opacity. Não anima o seletor de produtos, o plano calculado nem
// o assistente — essas áreas recalculam a cada tecla/clique (rows, budget,
// custom) e reanimar a cada recálculo pareceria quebrado/piscando, igual a
// uma página de resultados de busca.
useGSAP(() => {
  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
  gsap.from(".smart-basket-hero > *", { y: 16, opacity: 0, duration: .55, stagger: .06, ease: "power3.out" });
  gsap.from(".smart-controls > *", { y: 14, opacity: 0, duration: .5, delay: .12, stagger: .06, ease: "power2.out" });
  gsap.from(".smart-results .smart-strategies > *", { y: 14, opacity: 0, duration: .5, delay: .18, stagger: .06, ease: "power2.out" });
}, { scope: pageRef });

async function savePlan(){if(!profile||!supabase||!active.items.length)return;setSaving(true);setMessage("");const payload={user_id:profile.userId,name:`Cesta ${new Date().toLocaleDateString("pt-BR")}`,budget,household_income:income||null,household_size:people,strategy:active.strategy,total:active.total,savings:active.savings,store_count:active.stores.length,items:active.items.map(i=>({product_id:i.product.id,name:i.product.name,quantity:i.quantity,unit_price:i.offer.value,subtotal:i.subtotal,establishment:i.offer.establishment,establishment_id:i.offer.establishmentId}))};const{error}=await supabase.from("smart_basket_plans").insert(payload);setSaving(false);setMessage(error?`Não foi possível salvar: ${error.message}`:"Cesta salva na sua conta.");}
if(authLoading||loading)return <main className="smart-basket-state"><LoaderCircle className="spin"/><strong>Preparando sua cesta inteligente…</strong></main>;if(!profile)return null;
return <><div className="smart-basket-page" ref={pageRef}><PublicHeader current="basket"/><main id="conteudo-principal" className="smart-basket-shell">
<section className="smart-basket-hero"><div><small>PLANEJAMENTO DE COMPRA</small><h1>Monte a melhor cesta para o dinheiro que você tem.</h1><p>Use nossa sugestão de itens essenciais ou escolha exatamente os produtos que deseja comprar.</p></div><ShoppingBasket/></section>
<section className="smart-planner"><div className="smart-controls"><label><span><WalletCards/> Quanto você tem disponível?</span><div className="money-input"><b>R$</b><input type="number" min="10" step="10" value={budget} onChange={e=>setBudget(Math.max(0,Number(e.target.value)))}/></div></label><label><span>Renda mensal da família <em>opcional</em></span><div className="money-input"><b>R$</b><input type="number" min="0" step="100" value={income} placeholder="Ex.: 2.500" onChange={e=>setIncome(e.target.value===""?"":Number(e.target.value))}/></div>{suggestedBudget&&<button type="button" className="budget-suggestion" onClick={()=>setBudget(suggestedBudget)}>Usar referência de {brl.format(suggestedBudget)} <small>25% da renda · ajustável</small></button>}</label><label><span>Pessoas na casa</span><select value={people} onChange={e=>setPeople(Number(e.target.value))}>{[1,2,3,4,5,6,7,8].map(n=><option key={n}>{n}</option>)}</select></label></div></section>
<section className="smart-product-picker"><header><div><small>PRODUTOS DA CESTA</small><h2>Como você quer montar sua lista?</h2></div><div className="smart-picker-tabs"><button className={selectionMode==="smart"?"is-active":""} onClick={()=>setSelectionMode("smart")}><Sparkles/> Sugestão inteligente</button><button className={selectionMode==="custom"?"is-active":""} onClick={()=>setSelectionMode("custom")}><PackagePlus/> Escolher meus produtos</button></div></header>{selectionMode==="custom"&&<><div className="smart-product-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque arroz, café, leite, frango, marca..."/></div>{searchResults.length>0&&<div className="smart-product-results">{searchResults.map(product=><button key={String(product.id)} onClick={()=>addProduct(product)}><span><strong>{product.name}</strong><small>{product.brand||product.category} · a partir de {brl.format(product.minPrice)}</small></span><Plus/></button>)}</div>}<div className="smart-custom-list">{customRows.length?customRows.map(row=><article key={String(row.product.id)}><div><strong>{row.product.name}</strong><small>{row.product.brand||row.product.category} · menor preço {brl.format(row.product.minPrice)}</small></div><div className="smart-qty"><button onClick={()=>changeQty(String(row.product.id),-1)} aria-label="Diminuir quantidade"><Minus/></button><b>{row.quantity}</b><button onClick={()=>changeQty(String(row.product.id),1)} aria-label="Aumentar quantidade"><Plus/></button></div><button className="smart-remove" onClick={()=>setCustom(current=>{const copy={...current};delete copy[row.product.id];return copy;})} aria-label={`Remover ${row.product.name}`}><Trash2/></button></article>):<div className="smart-custom-empty"><PackagePlus/><strong>Sua seleção está vazia.</strong><span>Pesquise acima e adicione os produtos que deseja comprar.</span></div>}</div></>}</section>
<section className="smart-results"><header><div><small>COMPARAÇÃO AUTOMÁTICA</small><h2>Escolha como quer comprar</h2></div><strong>Orçamento: {brl.format(budget)}</strong></header><div className="smart-strategies"><button type="button" className={selected==="multi_store"?"is-active":""} onClick={()=>setSelected("multi_store")}><span className="strategy-icon"><PiggyBank/></span><span><small>MAIOR ECONOMIA</small><strong>Menores preços em várias lojas</strong><em>O sistema escolhe a oferta mais barata de cada produto.</em></span><b>{brl.format(multi.total)}</b><i>{multi.stores.length} {multi.stores.length===1?"loja":"lojas"}</i></button><button type="button" className={selected==="single_store"?"is-active":""} onClick={()=>setSelected("single_store")}><span className="strategy-icon"><Store/></span><span><small>MAIS PRATICIDADE</small><strong>Melhor compra em uma loja</strong><em>{single.storeName?`Melhor combinação em ${single.storeName}.`:"Procura uma loja com a melhor combinação."}</em></span><b>{brl.format(single.total)}</b><i>{single.items.length} produtos atendidos</i></button></div></section>
<section className="smart-plan"><div className="smart-plan-list"><header><span><CheckCircle2/><div><small>CESTA CALCULADA</small><h2>{active.label}</h2></div></span><strong>{active.items.reduce((s,i)=>s+i.quantity,0)} unidades</strong></header>{active.items.map(item=><article key={`${item.product.id}-${item.offer.establishment}`}><div><small>{item.essential}</small><strong>{item.product.name}</strong><em>{item.product.size} · {item.offer.establishment}</em></div><span>{item.quantity} × {brl.format(item.offer.value)}</span><b>{brl.format(item.subtotal)}</b></article>)}{!active.items.length&&<div className="smart-empty">{selectionMode==="custom"&&!customRows.length?"Escolha ao menos um produto para calcular sua cesta.":"Nenhum item cabe neste orçamento com os preços disponíveis."}</div>}</div><aside className="smart-summary"><small>RESUMO</small><h2>{brl.format(active.total)}</h2><div><span>Saldo do orçamento</span><strong>{brl.format(Math.max(0,budget-active.total))}</strong></div><div><span>Estabelecimentos</span><strong>{active.stores.length}</strong></div><div><span>Produtos não atendidos</span><strong>{active.missing.length}</strong></div><button type="button" disabled={saving||!active.items.length} onClick={savePlan}>{saving?<LoaderCircle className="spin"/>:<Save/>}{saving?"Salvando…":"Salvar esta cesta"}</button>{message&&<p className={message.startsWith("Cesta salva")?"success":"error"}>{message}</p>}<Link to="/buscar"><Building2/> Explorar catálogo</Link></aside></section>

<button type="button" className="smart-assistant-fab" onClick={()=>setAssistantOpen(v=>!v)} aria-expanded={assistantOpen} aria-label={assistantOpen?"Fechar assistente":"Abrir assistente de compras"}>{assistantOpen?<X/>:<Bot/>}{!assistantOpen&&<span>Assistente</span>}</button>
{assistantOpen&&<aside className="smart-assistant" role="dialog" aria-label="Assistente de compras PreçoCerto">
<header><span className="smart-assistant__avatar"><Bot/></span><div><strong>Assistente PreçoCerto</strong><small>Ajuda a montar sua cesta mais rápido</small></div><button type="button" onClick={()=>setAssistantOpen(false)} aria-label="Fechar assistente"><X/></button></header>
<div className="smart-assistant__log" ref={assistantLogRef}>{assistantLog.map((turn,index)=><p key={index} className={turn.from}>{turn.text}</p>)}</div>
<div className="smart-assistant__chips">{ASSISTANT_CHIPS.map(chip=><button key={chip} type="button" onClick={()=>askAssistant(chip)}>{chip}</button>)}</div>
<form className="smart-assistant__form" onSubmit={submitAssistant}><input value={assistantInput} onChange={e=>setAssistantInput(e.target.value)} placeholder="Ex.: arroz, 300, mais economia…" aria-label="Pergunte ao assistente"/><button type="submit" aria-label="Enviar"><Send/></button></form>
</aside>}
</main><AppDock current="basket"/></div>
<PublicFooter/></>;
}
