import { useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { Heart, LogOut, PackageSearch, ReceiptText, ShoppingBasket, Store, UserRound, ChevronDown, ShieldCheck, ArrowRight, LayoutDashboard, Sparkles } from "lucide-react";
import { loadSessionProfile, roleLabels, signOut, supabase, type SessionProfile } from "../lib/roles";
import { PublicFooter, PublicHeader } from "../reference/PublicChrome";
import "./UserAccountExperience.css";

function shortName(name: string) { const parts=name.trim().split(/\s+/).filter(Boolean); return parts.length>1?`${parts[0]} ${parts[parts.length-1]}`:parts[0]||"Minha conta"; }
function initials(name:string){return name.trim().split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join("")||"PC";}
export function useCurrentProfile(){const[profile,setProfile]=useState<SessionProfile|null>(null);const[loading,setLoading]=useState(true);useEffect(()=>{let active=true;const refresh=async()=>{const next=await loadSessionProfile();if(!active)return;setProfile(next);setLoading(false);document.body.classList.toggle("pc-authenticated",Boolean(next));};void refresh();window.addEventListener("pc:auth-changed",refresh);const subscription=supabase?.auth.onAuthStateChange(()=>{window.setTimeout(()=>void refresh(),0);});return()=>{active=false;window.removeEventListener("pc:auth-changed",refresh);subscription?.data.subscription.unsubscribe();document.body.classList.remove("pc-authenticated");};},[]);return{profile,loading};}
function AccountMenu({profile,onClose}:{profile:SessionProfile;onClose:()=>void}){const navigate=useNavigate();const role=profile.roles[0]?roleLabels[profile.roles[0]]:"Consumidor";const merchant=profile.roles.some(item=>item==="merchant_owner"||item==="merchant_staff");const admin=profile.isAdmin;const logout=async()=>{await signOut();onClose();navigate("/");};return <div className="pc-user-menu" role="menu"><header><span className="pc-user-avatar">{initials(profile.name)}</span><span><strong>{profile.name}</strong><small>{profile.email}</small><em>{role}</em></span></header><nav>{admin&&<Link to="/admin" onClick={onClose}><ShieldCheck /><span><strong>Painel administrativo</strong><small>Controle completo da plataforma</small></span></Link>}<Link to="/minha-conta" onClick={onClose}><UserRound /><span><strong>Minha conta</strong><small>Visão geral e atalhos</small></span></Link><Link to="/favoritos" onClick={onClose}><Heart /><span><strong>Favoritos</strong><small>Produtos que você acompanha</small></span></Link><Link to="/cesta-basica" onClick={onClose}><ShoppingBasket /><span><strong>Minha lista</strong><small>Cesta e total estimado</small></span></Link><Link to="/cesta-inteligente" onClick={onClose}><Sparkles /><span><strong>Cesta inteligente</strong><small>Monte uma compra dentro do orçamento</small></span></Link><Link to="/meus-pedidos" onClick={onClose}><ReceiptText /><span><strong>Meus pedidos</strong><small>Acompanhe suas compras</small></span></Link>{merchant&&<Link to="/painel-lojista" onClick={onClose}><Store /><span><strong>Minha loja</strong><small>Gerencie catálogo e vendas</small></span></Link>}</nav><button type="button" onClick={logout}><LogOut /> Sair da conta</button></div>;}
function HeaderAccount({profile}:{profile:SessionProfile}){const[open,setOpen]=useState(false);const rootRef=useRef<HTMLDivElement>(null);const location=useLocation();useEffect(()=>setOpen(false),[location.pathname]);useEffect(()=>{if(!open)return;const close=(event:PointerEvent)=>{if(!rootRef.current?.contains(event.target as Node))setOpen(false);};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close);},[open]);return <div className="pc-user-root" ref={rootRef}><button className="pc-user-trigger" type="button" aria-expanded={open} onClick={()=>setOpen(value=>!value)}><span className="pc-user-avatar">{initials(profile.name)}</span><span className="pc-user-trigger__text"><small>{profile.isAdmin?"Admin":"Olá,"}</small><strong>{shortName(profile.name)}</strong></span><ChevronDown /></button>{open&&<AccountMenu profile={profile} onClose={()=>setOpen(false)}/>}</div>;}
export function UserAccountHub(){const{profile}=useCurrentProfile();const[target,setTarget]=useState<Element|null>(null);const location=useLocation();useEffect(()=>{if(!profile){setTarget(null);return;}const find=()=>{const next=document.querySelector(".mh26-head-actions")||document.querySelector(".nx-header__actions")||document.querySelector(".hp-header__actions")||document.querySelector(".ref-header__actions")||document.querySelector(".pdp-topbar nav");setTarget(next);};find();const frame=window.requestAnimationFrame(find);return()=>window.cancelAnimationFrame(frame);},[profile,location.pathname]);if(!profile)return null;const element=<HeaderAccount profile={profile}/>;return target?createPortal(element,target):<div className="pc-user-floating">{element}</div>;}
export function UserAccountPage(){const{profile,loading}=useCurrentProfile();const merchant=useMemo(()=>Boolean(profile?.roles.some(item=>item==="merchant_owner"||item==="merchant_staff")),[profile]);if(loading)return <main className="pc-account-state"><span className="pc-account-loader"/><p>Carregando sua conta…</p></main>;if(!profile)return <main className="pc-account-state"><UserRound/><h1>Entre para acessar sua conta</h1><p>Favoritos, listas e pedidos ficam disponíveis quando sua conta está conectada.</p><Link to="/login?redirect=/minha-conta">Entrar na minha conta <ArrowRight/></Link></main>;return <div className="pc-account-page"><PublicHeader current="profile"/><main id="conteudo-principal" className="pc-account-shell"><section className="pc-account-hero"><span className="pc-user-avatar pc-user-avatar--hero">{initials(profile.name)}</span><div><small>{profile.isAdmin?"ADMINISTRAÇÃO PREÇOCERTO":"SEU ESPAÇO NO PREÇOCERTO"}</small><h1>Olá, {profile.name.split(" ")[0]}.</h1><p>{profile.isAdmin?"Sua conta possui acesso administrativo à plataforma, operações, comerciantes e usuários.":"Seus atalhos para acompanhar produtos, organizar compras e usar o marketplace com mais praticidade."}</p></div><span className="pc-account-verified"><ShieldCheck/> {profile.isAdmin?"Administrador verificado":"Conta conectada"}</span></section><section className="pc-account-tools" aria-label="Ferramentas da conta">{profile.isAdmin&&<Link to="/admin"><LayoutDashboard/><span><strong>Abrir painel administrativo</strong><small>Controle e acompanhe toda a plataforma.</small></span><ArrowRight/></Link>}<Link to="/favoritos"><Heart/><span><strong>Favoritos</strong><small>Acompanhe os produtos que você salvou.</small></span><ArrowRight/></Link><Link to="/cesta-basica"><ShoppingBasket/><span><strong>Lista de compras</strong><small>Veja itens e total estimado da sua cesta.</small></span><ArrowRight/></Link><Link to="/cesta-inteligente"><Sparkles/><span><strong>Cesta inteligente</strong><small>Monte uma cesta dentro do seu orçamento e compare estratégias.</small></span><ArrowRight/></Link><Link to="/meus-pedidos"><ReceiptText/><span><strong>Meus pedidos</strong><small>Acompanhe compras feitas em estabelecimentos participantes.</small></span><ArrowRight/></Link><Link to="/buscar"><PackageSearch/><span><strong>Continuar comprando</strong><small>Pesquise produtos e compare preços locais.</small></span><ArrowRight/></Link>{merchant&&<Link to="/painel-lojista"><Store/><span><strong>Gerenciar meu estabelecimento</strong><small>Catálogo, vendas e presença no marketplace.</small></span><ArrowRight/></Link>}</section><section className="pc-account-details"><div><small>NOME</small><strong>{profile.name}</strong></div><div><small>E-MAIL</small><strong>{profile.email||"Não informado"}</strong></div><div><small>PERFIL</small><strong>{profile.roles.map(role=>roleLabels[role]).join(" · ")}</strong></div></section></main><PublicFooter/></div>;}
